[package]
name = "minikafka"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pin-project-lite = "0.2"
thiserror = "1.0"
tokio = {version = "1.14", default-features = false, features = ["io-util", "net"]}

[dev-dependencies]
assert_matches = "1.5"
proptest = "1"
proptest-derive = "0.3"
tokio = {version = "1.14", features = ["macros", "rt"]}
